vpn:
  name: Super-Happiness
  description: Advanced Custom VPN using GitHub Pages
  location: US East
  protocol: OpenVPN
  port: 1194
  credentials:
    username: username
    password: password

domain:
  name: super-happiness.com
  ssl_certificate: /path/to/ssl_certificate.crt

settings:
  production: true
  future_proof: true
  optimize: true
  extend: true
  customize: true
