name: GitHub Pages workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          branch: gh-pages
          folder: dist